apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
  namespace: coresupply-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: core-catalogdb # ??? DNS ???? ??????
  namespace: coresupply-ns
spec:
  selector:
    app: catalogdb
  ports:
    - port: 27017
      targetPort: 27017
---
# ????? ??????? ???? Quote (?? ??????? ?? ???? ??????? ????? ??????? ???)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotedb
  namespace: coresupply-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotedb
  template:
    metadata:
      labels:
        app: quotedb
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: core-quotedb
  namespace: coresupply-ns
spec:
  selector:
    app: quotedb
  ports:
    - port: 27017
      targetPort: 27017