apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-grpc
  namespace: coresupply-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-grpc
  template:
    metadata:
      labels:
        app: discount-grpc
    spec:
      containers:
        - name: discount-grpc
          image: discountgrpc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DatabaseSettings__ConnectionString
              value: "Data Source=DiscountDb.db"
            - name: Kestrel__EndpointDefaults__Protocols
              value: "Http2"
---
apiVersion: v1
kind: Service
metadata:
  name: discount-grpc
  namespace: coresupply-ns
spec:
  selector:
    app: discount-grpc
  ports:
    - port: 8080
      targetPort: 8080
      name: grpc