apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: coresupply-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
        - name: quote-api
          image: quoteapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DatabaseSettings__ConnectionString
              value: "mongodb://core-quotedb:27017"
            - name: CacheSettings__ConnectionString
              value: "core-redis:6379"
            - name: GrpcSettings__DiscountUrl
              value: "http://discount-grpc:8080" # ??? ????? K8s
            - name: EventBusSettings__HostAddress
              value: "amqp://guest:guest@core-eventbus:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: quote-api
  namespace: coresupply-ns
spec:
  selector:
    app: quote-api
  ports:
    - port: 80
      targetPort: 8080